name: "Publish Documentation"

on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        target_branch: 'dev/automated-updates-${GITHUB_SHA}'
        documentation_path: './docs/source'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: 'gh-pages'
        delete-branch: true
        title: 'gh-pages updates from ${GITHUB_SHA}'
        branch: dev/automated-updates-${GITHUB_SHA}
        body: 'Automated updates to published pages from ${GITHUB_SHA}'